### ISSUE TITLE
Code modernization

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/ckanext-scheming#3]
> The GIS Hub uses a customized version of the ckanext-scheming extension, which supports customizable metadata schemas for datasets and resources. The version used on our system has diverged so much from the "official" version of this extension that they are no longer compatible.

The goal is to support running this extension against CKAN 2.9 in both a Python 2 and Python 3 environments.
Please refer to the main documentation for [Python 3 extensions migration](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions).

__Is it possible to merge the official repo with the GIS Hub repo?  I don't see how that would work.__

@genkimaps can you add me as an editor or contributor to this repo? As it is, I don't think I am.

Tasks:

- [ ] Code modernization ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#code-modernization))
  * [ ] Convert controllers to flask views/blueprints ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#convert-controllers-to-flask-viewsblueprints))
  * [ ] Import from core ckan using toolkit ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#import-from-core-ckan-using-toolkit))
  * [ ] Dependencies must be python 3 compatible ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#dependencies-must-be-python-3-compatible))
  * [ ] Update Travis CI config ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#update-travis-ci-config))
  * [ ] Compatibility table ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#compatibility-table))
  * [ ] Release modernized version ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#release-modernized-version))
- [ ] Python 3 preparation ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#python-3-preparation))
  * [ ] Create a separate WIP branch ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#create-a-separate-wip-branch))
  * [ ] Create mixin plugin implementations for Pylons / Flask ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#create-mixin-plugin-implementations-for-pylons--flask))
  * [ ] Command line commands ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#command-line-commands))
  * [ ] Web assets ([docs](JS and CSS) [docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#web-assets--js-and-css-))
  * [ ] Templates ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#templates))
  * [ ] Test suite ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#test-suite))
  * [ ] Running tests for Python 2 and 3 on Travis ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#running-tests-for-python-2-and-3-on-travis))
  * [ ] Fix Python 3 issues / futurize code ([docs](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#fix-python-3-issues--futurize-code))

**Comment by cole-fields** [comment]
@genkimaps when we have our code review/catch up call, we should discuss the scheming extension. My main concern is that I don't want to duplicate efforts that have been done by the maintainers of the official repo for upgrading to a ckan 2.9 compatible version. But we also have an extensively customized repo used for our instance. 

Basically my question is do you think we should (a) pull from the official repo and update it to suit our needs again rather than (b) updating our own to make it compatible with 2.9? I will look into it, but my thinking is that option a is probably simpler.

**Comment by genkimaps** [comment]
@cole-fields As discussed, most of the tasks above should not be needed. Try to use mainstream ckanext-scheming, only update if needed. See list of changes that were customized for DFO here: https://github.com/genkimaps/ckanext-scheming/commits/dfo

**Comment by genkimaps** [comment]
@cole-fields  I'm using the default version of this extension on the CKAN 2.9 server, and it seems to work fine. I think we can close this issue.
